#ifndef AD7293_H
#define AD7293_H

#include "defines.h"

#define AD7293_ID           0x0018

#define AD7293_OP_READ      0x80
#define AD7293_OP_WRITE     0x00

/**< Internal reference voltage */
#define AD7293_REF_VOLTAGE          1.25f
#define AD7293_CURRENT_GAIN         6.25f
#define AD7293_SHUNT                0.027f

/**< Temperature channels */
enum {
  AD7293_TEMPERATURE_INT,
  AD7293_TEMPERATURE_D0,
  AD7293_TEMPERATURE_D1,
  AD7293_TEMPERATURE_LAST
};

/**< Pages */
#define REGISTER_PAGE_RESULT_0      0x00
#define REGISTER_PAGE_RESULT_1      0x01
#define REGISTER_PAGE_CONFIGURATION 0x02
#define REGISTER_HIGH_LIMIT_0       0x04
#define REGISTER_HIGH_LIMIT_1       0x05
#define REGISTER_LOW_LIMIT_0        0x06
#define REGISTER_LOW_LIMIT_1        0x07
#define REGISTER_PAGE_OFFSET0       0x0E
#define REGISTER_PAGE_OFFSET1       0x0F
#define REGISTER_ALERT              0x10
#define REGISTER_ALERT0_PAGE        0x11
#define REGISTER_ALERT1_PAGE        0x12

/**< Common registers */
#define REGISTER_COMMON_NOOP                0x00
#define REGISTER_COMMON_PAGE_SELECT_POINTER 0x01 /*  */
#define REGISTER_COMMON_CONVERSION_COMMAND  0x02 /*  */
#define REGISTER_COMMON_RESULT              0x03 /*  */
#define REGISTER_COMMON_DAC_ENABLE          0x04 /*  */
#define REGISTER_COMMON_GPIO                0x05 /*  */
#define REGISTER_COMMON_DEVICE_ID           0x0C /*  */
#define REGISTER_COMMON_SOFTWARE_RESET      0x0F /*   */

/**< Register: GPIO Register, 0x05 */
#define REGISTER_COMMON_GPIO_GPIO0  0x01
#define REGISTER_COMMON_GPIO_GPIO1  0x02
#define REGISTER_COMMON_GPIO_GPIO2  0x04
#define REGISTER_COMMON_GPIO_GPIO3  0x08
#define REGISTER_COMMON_GPIO_GPIO4  0x10
#define REGISTER_COMMON_GPIO_GPIO5  0x20
#define REGISTER_COMMON_GPIO_GPIO6  0x40
#define REGISTER_COMMON_GPIO_GPIO7  0x80

/**< Page: RESULT0 (0x00) */
#define REGISTER_RESULT_0_VIN0      0x10
#define REGISTER_RESULT_0_VIN1      0x11
#define REGISTER_RESULT_0_VIN2      0x12
#define REGISTER_RESULT_0_VIN3      0x13
#define REGISTER_RESULT_0_TSENSEINT 0x20 /*   */
#define REGISTER_RESULT_0_TSENSED0  0x21 /*   */
#define REGISTER_RESULT_0_TSENSED1  0x22 /*   */
#define REGISTER_RESULT_0_ISENSE0   0x28 /*   */
#define REGISTER_RESULT_0_ISENSE1   0x29 /*   */
#define REGISTER_RESULT_0_ISENSE2   0x2A /*   */
#define REGISTER_RESULT_0_ISENSE3   0x2B /*   */
#define REGISTER_RESULT_0_UNI_VOUT0 0x30 /*   */
#define REGISTER_RESULT_0_UNI_VOUT1 0x31 /*   */
#define REGISTER_RESULT_0_UNI_VOUT2 0x32 /*   */
#define REGISTER_RESULT_0_UNI_VOUT3 0x33 /*   */
#define REGISTER_RESULT_0_BI_VOUT0  0x34 /*   */
#define REGISTER_RESULT_0_BI_VOUT1  0x35 /*   */
#define REGISTER_RESULT_0_BI_VOUT2  0x36 /*   */
#define REGISTER_RESULT_0_BI_VOUT3  0x37 /*   */

/**< Page: RESULT1 (0x01) */
#define REGISTER_RESULT_1_AVDD      0x10
#define REGISTER_RESULT_1_DAC_UNI   0x11
#define REGISTER_RESULT_1_DAC_BI    0x12
#define REGISTER_RESULT_1_AVSS      0x13
#define REGISTER_RESULT_1_BI_VOUT_0 0x14
#define REGISTER_RESULT_1_BI_VOUT_1 0x15
#define REGISTER_RESULT_1_BI_VOUT_2 0x16
#define REGISTER_RESULT_1_BI_VOUT_3 0x17
#define REGISTER_RESULT_1_RS_0      0x28
#define REGISTER_RESULT_1_RS_1      0x29
#define REGISTER_RESULT_1_RS_2      0x2A
#define REGISTER_RESULT_1_RS_3      0x2B

/**< Page: CONFIGURATION (0x02) */
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_ENABLE     0x11
#define REGISTER_CONFIGURATION_DIGITAL_IO_FUNCTION       0x12
#define REGISTER_CONFIGURATION_DIGITAL_FUNCTION_POLARITY 0x13
#define REGISTER_CONFIGURATION_GENERAL                   0x14
#define REGISTER_CONFIGURATION_VINX_FILTER               0x18
#define REGISTER_CONFIGURATION_VINX_ENABLE               0x19
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE 0x1B
#define REGISTER_CONFIGURATION_ISENSX_ENABLE             0x1C
#define REGISTER_CONFIGURATION_ISENS_X_GAIN              0x1D
#define REGISTER_CONFIGURATION_CLOSE_LOOP_CONTROL        0x28
#define REGISTER_CONFIGURATION_MON_ENABLE                0x23
#define REGISTER_CONFIGURATION_PA_ON_CONTROL             0x29
#define REGISTER_CONFIGURATION_RAMP_TIME_0               0x2A
#define REGISTER_CONFIGURATION_RAMP_TIME_1               0x2B
#define REGISTER_CONFIGURATION_RAMP_TIME_2               0x2C
#define REGISTER_CONFIGURATION_RAMP_TIME_3               0x2D

/**< Register: Digital Output Enable Register, 0x11 */
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO0      0x0001
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO1      0x0002
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO2      0x0004
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO3      0x0008
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO4      0x0010
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO5      0x0020
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO6      0x0040
#define REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO7      0x0080

#define DIGITAL_OUTPUT_DEFAULT    (REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO0 | \
                                   REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO1 | \
                                   REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO2 | \
                                   REGISTER_CONFIGURATION_DIGITAL_OUTPUT_GPIO3)

/**< Register: General, 0x14 */
#define REGISTER_CONFIGURATION_GENERAL_ADC_REF_INT       0x0080

/**< Register: TSENSEx background enable, 0x1B */
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE_INT        0x0001
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE_D1         0x0002
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE_D2         0x0004
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE_INT_FILTER 0x0100
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE_D1_FILTER  0x0200
#define REGISTER_CONFIGURATION_TEMPERATURE_SENSOR_ENABLE_D2_FILTER  0x0400

/**< Register: ISENSEx background enable, 0x1C */
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_0           0x0001
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_1           0x0002
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_2           0x0004
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_3           0x0008
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_0_FILTER    0x0100
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_1_FILTER    0x0200
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_2_FILTER    0x0400
#define REGISTER_CONFIGURATION_ISENSX_ENABLE_3_FILTER    0x0800

/**< Register: Current Sensor Gain Register, 0x1D */
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_6_25         0x00
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_12_5         0x01
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_18_75        0x02
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_25           0x03
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_37_5         0x04
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_50           0x05
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_75           0x05
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_100          0x07
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_200          0x08
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_400          0x09
#define REGISTER_CONFIGURATION_ISENS_X_GAIN_781_2        0x0A

#define REGISTER_CONFIGURATION_ISENS_0_SET(v)           (v << 0)
#define REGISTER_CONFIGURATION_ISENS_1_SET(v)           (v << 4)
#define REGISTER_CONFIGURATION_ISENS_2_SET(v)           (v << 8)
#define REGISTER_CONFIGURATION_ISENS_3_SET(v)           (v << 12)

/**< Register: Background Enable Register, 0x23 */
#define REGISTER_CONFIGURATION_MON_ENABLE_RS3            0x0800
#define REGISTER_CONFIGURATION_MON_ENABLE_RS2            0x0400
#define REGISTER_CONFIGURATION_MON_ENABLE_RS1            0x0200
#define REGISTER_CONFIGURATION_MON_ENABLE_RS0            0x0100
#define REGISTER_CONFIGURATION_MON_ENABLE_BIVOUT3        0x0080
#define REGISTER_CONFIGURATION_MON_ENABLE_BIVOUT2        0x0040
#define REGISTER_CONFIGURATION_MON_ENABLE_BIVOUT1        0x0020
#define REGISTER_CONFIGURATION_MON_ENABLE_BIVOUT0        0x0010
#define REGISTER_CONFIGURATION_MON_ENABLE_AVSS           0x0008
#define REGISTER_CONFIGURATION_MON_ENABLE_DACVBI         0x0004
#define REGISTER_CONFIGURATION_MON_ENABLE_DACVUNI        0x0002
#define REGISTER_CONFIGURATION_MON_ENABLE_AVDD           0x0001

/**< Register: PA_ON control, 0x29 */
#define REGISTER_CONFIGURATION_PA_ON_ENABLE              0x200

/**< Page: HIGHLIMIT0 (0x04) */
#define REGISTER_HIGH_LIMIT_0_VIN0      0x10
#define REGISTER_HIGH_LIMIT_0_VIN1      0x11
#define REGISTER_HIGH_LIMIT_0_VIN2      0x12
#define REGISTER_HIGH_LIMIT_0_VIN3      0x13
#define REGISTER_HIGH_LIMIT_0_TSENSEINT 0x20
#define REGISTER_HIGH_LIMIT_0_TSENSED0  0x21
#define REGISTER_HIGH_LIMIT_0_TSENSED1  0x22
#define REGISTER_HIGH_LIMIT_0_ISENSE0   0x28
#define REGISTER_HIGH_LIMIT_0_ISENSE1   0x29
#define REGISTER_HIGH_LIMIT_0_ISENSE2   0x2A
#define REGISTER_HIGH_LIMIT_0_ISENSE3   0x2B

/**< Page: HIGHLIMIT1 (0x05) */
#define REGISTER_HIGH_LIMIT_1_AVDD      0x10
#define REGISTER_HIGH_LIMIT_1_DAC_UNI   0x11
#define REGISTER_HIGH_LIMIT_1_DAC_BI    0x12
#define REGISTER_HIGH_LIMIT_1_AVSS      0x13
#define REGISTER_HIGH_LIMIT_1_BI_VOUT_0 0x14
#define REGISTER_HIGH_LIMIT_1_BI_VOUT_1 0x15
#define REGISTER_HIGH_LIMIT_1_BI_VOUT_2 0x16
#define REGISTER_HIGH_LIMIT_1_BI_VOUT_3 0x17
#define REGISTER_HIGH_LIMIT_1_RS_0      0x28
#define REGISTER_HIGH_LIMIT_1_RS_1      0x29
#define REGISTER_HIGH_LIMIT_1_RS_2      0x2A
#define REGISTER_HIGH_LIMIT_1_RS_3      0x2B

/**< Page: LOWLIMIT0 (0x06) */
#define REGISTER_LOW_LIMIT_0_VIN0       0x10
#define REGISTER_LOW_LIMIT_0_VIN1       0x11
#define REGISTER_LOW_LIMIT_0_VIN2       0x12
#define REGISTER_LOW_LIMIT_0_VIN3       0x13
#define REGISTER_LOW_LIMIT_0_TSENSEINT  0x20
#define REGISTER_LOW_LIMIT_0_TSENSED0   0x21
#define REGISTER_LOW_LIMIT_0_TSENSED1   0x22
#define REGISTER_LOW_LIMIT_0_ISENSE0    0x28
#define REGISTER_LOW_LIMIT_0_ISENSE1    0x29
#define REGISTER_LOW_LIMIT_0_ISENSE2    0x2A
#define REGISTER_LOW_LIMIT_0_ISENSE3    0x2B

/**< Page: LOWLIMIT0 (0x07) */
#define REGISTER_LOW_LIMIT_1_AVDD       0x10
#define REGISTER_LOW_LIMIT_1_DAC_UNI    0x11
#define REGISTER_LOW_LIMIT_1_DAC_BI     0x12
#define REGISTER_LOW_LIMIT_1_AVSS       0x13
#define REGISTER_LOW_LIMIT_1_BI_VOUT_0  0x14
#define REGISTER_LOW_LIMIT_1_BI_VOUT_1  0x15
#define REGISTER_LOW_LIMIT_1_BI_VOUT_2  0x16
#define REGISTER_LOW_LIMIT_1_BI_VOUT_3  0x17
#define REGISTER_LOW_LIMIT_1_RS_0       0x28
#define REGISTER_LOW_LIMIT_1_RS_1       0x29
#define REGISTER_LOW_LIMIT_1_RS_2       0x2A
#define REGISTER_LOW_LIMIT_1_RS_3       0x2B

/**< Page: OFFSET0 (0x0E) */
#define REGISTER_OFFSET_0_VIN0      0x10
#define REGISTER_OFFSET_0_VIN1      0x11
#define REGISTER_OFFSET_0_VIN2      0x12
#define REGISTER_OFFSET_0_VIN3      0x13
#define REGISTER_OFFSET_0_ISENS0_OFFSET     0x28
#define REGISTER_OFFSET_0_UNI_VOUT0_OFFSET  0x30
#define REGISTER_OFFSET_0_UNI_VOUT1_OFFSET  0x31
#define REGISTER_OFFSET_0_UNI_VOUT2_OFFSET  0x32
#define REGISTER_OFFSET_0_UNI_VOUT3_OFFSET  0x33
#define REGISTER_OFFSET_0_BI_VOUT0_OFFSET   0x34
#define REGISTER_OFFSET_0_BI_VOUT1_OFFSET   0x35
#define REGISTER_OFFSET_0_BI_VOUT2_OFFSET   0x36
#define REGISTER_OFFSET_0_BI_VOUT3_OFFSET   0x37

/**< Page: OFFSET1 (0x0F) */
#define REGISTER_PAGE_OFFSET1_AVDD  0x10

/**< Page: ALERT (0x10) */
#define REGISTER_ALERT_SUM          0x10
#define REGISTER_ALERT_VINX         0x12
#define REGISTER_ALERT_TSENSX       0x14
#define REGISTER_ALERT_ISENSX       0x15
#define REGISTER_ALERT_BIVOUTX      0x18
#define REGISTER_ALERT_RSXMON       0x19
#define REGISTER_ALERT_INTLIMITX    0x1A

/**< Register: Alert Summary, 0x10 */
#define REGISTER_ALERT_SUM_RSX_HIGH      0x8000
#define REGISTER_ALERT_SUM_BIVXOUT_HIGH  0x4000
#define REGISTER_ALERT_SUM_ISENSX_HIGH   0x0800
#define REGISTER_ALERT_SUM_TSENSX_HIGH   0x0400
#define REGISTER_ALERT_SUM_VINX_HIGH     0x0100
#define REGISTER_ALERT_SUM_RSX_LOW       0x0080
#define REGISTER_ALERT_SUM_BIVXOUT_LOW   0x0040
#define REGISTER_ALERT_SUM_ISENSX_LOW    0x0008
#define REGISTER_ALERT_SUM_TSENSX_LOW    0x0004
#define REGISTER_ALERT_SUM_VINX_LOW      0x0001

/**< Register: Temperature Sensor (TSENSEx) Alert, 0x14 */
#define REGISTER_ALERT_TSENSX_HIGH_D1    0x0400
#define REGISTER_ALERT_TSENSX_HIGH_D0    0x0200
#define REGISTER_ALERT_TSENSX_HIGH_INT   0x0100
#define REGISTER_ALERT_TSENSX_LOW_D1     0x0004
#define REGISTER_ALERT_TSENSX_LOW_D0     0x0002
#define REGISTER_ALERT_TSENSX_LOW_INT    0x0001

/**< Register: Current Sensor (ISENSEx) Alert, 0x15 */
#define REGISTER_ALERT_ISENSX_HIGH_3     0x0800
#define REGISTER_ALERT_ISENSX_HIGH_2     0x0400
#define REGISTER_ALERT_ISENSX_HIGH_1     0x0200
#define REGISTER_ALERT_ISENSX_HIGH_0     0x0100
#define REGISTER_ALERT_ISENSX_LOW_3      0x0008
#define REGISTER_ALERT_ISENSX_LOW_2      0x0004
#define REGISTER_ALERT_ISENSX_LOW_1      0x0002
#define REGISTER_ALERT_ISENSX_LOW_0      0x0001

/**< Page: ALERT0_PIN_ROUTING (0x11) */
#define REGISTER_ALERT0_PIN_VINX         0x12
#define REGISTER_ALERT0_PIN_TSENSX       0x14
#define REGISTER_ALERT0_PIN_ISENSX       0x15
#define REGISTER_ALERT0_PIN_BIVOUTX      0x18
#define REGISTER_ALERT0_PIN_RSXMON       0x19
#define REGISTER_ALERT0_PIN_INTLIMITX    0x1A

/**< Page: ALERT1_PIN_ROUTING (0x12) */
#define REGISTER_ALERT1_PIN_VINX         0x12
#define REGISTER_ALERT1_PIN_TSENSX       0x14
#define REGISTER_ALERT1_PIN_ISENSX       0x15
#define REGISTER_ALERT1_PIN_BIVOUTX      0x18
#define REGISTER_ALERT1_PIN_RSXMON       0x19
#define REGISTER_ALERT1_PIN_INTLIMITX    0x1A

/**< Register: Temperature Sensor (TSENSEx) Alert, 0x14 */
#define REGISTER_ALERT_PIN_TSENSX_HIGH_D1    0x0400
#define REGISTER_ALERT_PIN_TSENSX_HIGH_D0    0x0200
#define REGISTER_ALERT_PIN_TSENSX_HIGH_INT   0x0100
#define REGISTER_ALERT_PIN_TSENSX_LOW_D1     0x0004
#define REGISTER_ALERT_PIN_TSENSX_LOW_D0     0x0002
#define REGISTER_ALERT_PIN_TSENSX_LOW_INT    0x0001

/**< Register: Current Sensor (ISENSEx) Alert, 0x15 */
#define REGISTER_ALERT_PIN_ISENSX_HIGH_3     0x0800
#define REGISTER_ALERT_PIN_ISENSX_HIGH_2     0x0400
#define REGISTER_ALERT_PIN_ISENSX_HIGH_1     0x0200
#define REGISTER_ALERT_PIN_ISENSX_HIGH_0     0x0100
#define REGISTER_ALERT_PIN_ISENSX_LOW_3      0x0008
#define REGISTER_ALERT_PIN_ISENSX_LOW_2      0x0004
#define REGISTER_ALERT_PIN_ISENSX_LOW_1      0x0002
#define REGISTER_ALERT_PIN_ISENSX_LOW_0      0x0001

/**< Register: Power supply (RSx) Alert, 0x19 */
#define REGISTER_ALERT_PIN_RSX_HIGH_3        0x0800
#define REGISTER_ALERT_PIN_RSX_HIGH_2        0x0400
#define REGISTER_ALERT_PIN_RSX_HIGH_1        0x0200
#define REGISTER_ALERT_PIN_RSX_HIGH_0        0x0100
#define REGISTER_ALERT_PIN_RSX_LOW_3         0x0008
#define REGISTER_ALERT_PIN_RSX_LOW_2         0x0004
#define REGISTER_ALERT_PIN_RSX_LOW_1         0x0002
#define REGISTER_ALERT_PIN_RSX_LOW_0         0x0001

/**< Mask for alert */
#define AD7293_ALERTS_MASK          (REGISTER_ALERT_SUM_RSX_HIGH | REGISTER_ALERT_SUM_RSX_LOW | \
                                     REGISTER_ALERT_SUM_ISENSX_HIGH | \
                                     REGISTER_ALERT_SUM_TSENSX_HIGH | REGISTER_ALERT_SUM_TSENSX_LOW)

/**< Select GPIO pin for LDAC */
#define AD7293_LDAC_PIN             REGISTER_COMMON_GPIO_GPIO7

void AD7293_SetGateVoltage(uint8_t channel, int16_t voltage);
float AD7293_GetSupplyVoltage(uint8_t channel);
float AD7293_GetDrainCurrent(uint8_t channel);
float AD7293_GetTemperature(uint8_t channel);
uint16_t AD7293_GetAlerts(void);
uint16_t AD7293_GetTemperatureAlerts(void);
uint16_t AD7293_GetCurrentAlerts(void);
void AD7293_ResetAlerts(void);
void AD7293_SetGpio(uint8_t value);
void AD7293_SetPowerOn(void);
void AD7293_SetPowerOff(void);
void AD7293_EnablePowerMonitoring(void);
bool AD7293_Configuration(void);

#endif
